# Generated by Django 2.2.2 on 2019-11-15 07:33

import datetime
import django.contrib.auth.models
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopUserBasketView',
            fields=[
            ],
            options={
                'verbose_name': 'Пользователь с корзиной',
                'verbose_name_plural': 'пользователи с корзиной',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authapp.shopuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='shopuser',
            name='activation_key',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 17, 7, 33, 30, 762927, tzinfo=utc)),
        ),
    ]
