# Generated by Django 2.2.7 on 2019-11-19 13:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_auto_20191117_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuserprofile',
            name='city',
            field=models.CharField(blank=True, max_length=128, verbose_name='город'),
        ),
        migrations.AddField(
            model_name='shopuserprofile',
            name='country',
            field=models.CharField(blank=True, max_length=128, verbose_name='страна'),
        ),
        migrations.AddField(
            model_name='shopuserprofile',
            name='language',
            field=models.CharField(blank=True, max_length=2, verbose_name='язык'),
        ),
        migrations.AddField(
            model_name='shopuserprofile',
            name='link',
            field=models.CharField(blank=True, max_length=128, verbose_name='ссылка на страницу в VK'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 21, 13, 43, 44, 410, tzinfo=utc)),
        ),
    ]
