# Generated by Django 2.2.7 on 2019-12-09 08:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_auto_20191129_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 11, 8, 32, 35, 250208, tzinfo=utc)),
        ),
    ]
